# Gopkg dep config

[[constraint]]
  name = "github.com/dgraph-io/badger"
  branch = "master"

[[constraint]]
  name = "github.com/getsentry/raven-go"
  branch = "master"

[[constraint]]
  name = "github.com/go-yaml/yaml"
  branch = "master"

[[constraint]]
  name = "github.com/kdrag0n/discordgo"
  branch = "master"

[[constraint]]
  name = "go.uber.org/multierr"
  branch = "master"

[[constraint]]
  name = "go.uber.org/zap"
  branch = "master"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
